spring:
  application:
    name: demo
  profiles:
    # 기본적으로 활성화 될 프로파일
    active: API-KEY,dev
    # prod로 실행 시 활성화 될 프로파일
    group:
      prod: API-KEY

  # JPA
  jpa:
    database: mysql
    properties:
      hibernate:
        format_sql: 'true'



server:
  port: 8080
